{% set name = "markdown2" %}
{% set version = "2.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/markdown2-{{ version }}.tar.gz
  sha256: 4d502953a4633408b0ab3ec503c5d6984d1b14307e32b325ec7d16ea57524895

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - markdown2 = markdown2:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - markdown2
  commands:
    - pip check
    - markdown2 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trentm/python-markdown2
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A fast and complete Python implementation of Markdown

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - thewchan
