{% set name = "markdown2" %}
{% set version = "2.3.6" %}
{% set sha256 = "08a124043aa0ad36ba2136239547d5011a2b770278abb11a5609611e0040ea05" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - markdown2 = markdown2:main

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6

test:
  imports:
    - markdown2

  commands:
    - markdown2 --help

about:
  home: https://github.com/trentm/python-markdown2
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A fast and complete Python implementation of Markdown

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - themchan
