{% set name = "markdown2" %}
{% set version = "2.3.10" %}
{% set sha256 = "85956d8119fa6378156fef65545d66705a842819d2e1b50379a2b9d2aaa17cf0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - markdown2 = markdown2:main

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - markdown2

  commands:
    - markdown2 --help

about:
  home: https://github.com/trentm/python-markdown2
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A fast and complete Python implementation of Markdown

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
