{% set name = "markdown2" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/markdown2-{{ version }}.tar.gz
  sha256: 3ac02226a901c4b2f6fc21dbd17c26d118d2c25bcbb28cee093a1f8b5c46f3f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - markdown2 = markdown2:main

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - setuptools

  run:
    - python >=3.8,<4.0

test:
  imports:
    - markdown2

  commands:
    - pip check
    - markdown2 --help

  requires:
    - pip

about:
  home: https://github.com/trentm/python-markdown2
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A fast and complete Python implementation of Markdown

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - thewchan
