{% set name = "markdown2" %}
{% set version = "2.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/markdown2-{{ version }}.tar.gz
  sha256: c04841d0f9df37457396b9d73c54846ddb097a73e7eb7c81d1589e0bba566cda

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - markdown2 = markdown2:main

requirements:
  host:
    - pip
    - python >=3.7,<4.0

  run:
    - python >=3.7,<4.0

test:
  imports:
    - markdown2

  commands:
    - pip check
    - markdown2 --help

  requires:
    - pip

about:
  home: https://github.com/trentm/python-markdown2
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A fast and complete Python implementation of Markdown

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - thewchan
