{% set name = "markdown2" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/markdown2-{{ version }}.tar.gz
  sha256: 412520c7b6bba540c2c2067d6be3a523ab885703bf6a81d93963f848b55dfb9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - markdown2 = markdown2:main

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6

test:
  imports:
    - markdown2

  commands:
    - pip check
    - markdown2 --help

  requires:
    - pip

about:
  home: https://github.com/trentm/python-markdown2
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A fast and complete Python implementation of Markdown

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - thewchan
