appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
travis:
  secure:
    BINSTAR_TOKEN: i4XMNE84m8C2Is4l3lt+KQvK+fIiHp1eUTz6Pr1cm4FURdmnvOaSuGBIwKPPDgmxrpeNeL/KqELl0fq3Us1QOInbzBsX4eelgGKUhidaj6rt1e2JO74+2psA+YGyUntjURn49uW7aJXfipFq/BwNN31pG97mnUAq+JcZkkRpkY9OCsChrTOPP3dZStrhM+yGfIGlpHJboEzAr+gSeU0CoSEFZPWAK7tG6Pl27/CBX+O4Kx+V+hSW0L6X2HFYylunJsRAXlBgiCKAHDdUgMGxEgNkqy5DRXdv/JIx9SQn34bRMdTsIcLgnhLnmdQJBaIkuYWl8ChDgjjPVCBT+DkhvgswhDuYBdLdCrP9tJVs9GucQ6bJg2dEZCMpgkF5wFm5sCfk+B/UxYQoiG2l8Uy5fL/VXv+h/wKdwXa2NqpD+ZAIBGCuqbsu/ZGv+hWCLyrXjb/VRyZqvK1pKJuwoH5wGV1bVBYWKVHMGBIF5I8pkyOq0pJ6p9TuZ9hSws+a0c5eOaWQsqnu+PdkaPHTe7RSiJrU0kEhLqeTSgLH5JMKVjdhKX3acZqrewzNpklCfIOHy4xCcLwBZQSIUpCqIdocQ9shPoosSCXyPQwy3+9/VJdUWSBGI5PzJKDcC4TGn2EsaLJeAXUrUwOsd+FeJCDF1ad0X+olr7xsifMTaPibCms=
